action_mailer:
  address: smtp.mandrillapp.com
  port: 587
  enable_starttls_auto: true
  user_name: rubydn.com@gmail.com
  password: ZsXaafxYRDAp3QTRWmytbA
  authentication: login

devise:
  mailer_sender: rubydn.com@gmail.com

list_locales: [["English", "en"], ["Italian", "it"], ["French", "fr"], ["German", "de"]]

slack:
  webhook_url: https://hooks.slack.com/services/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
