devise:
  FB_APP_ID: 1486098568362378
  FB_APP_SECRET: 8ec12e102b130acfd4447234253f59db
  GG_APP_ID: '630017564342-bepruna5tsrmq9ojkvokknlt08sebu3a.apps.googleusercontent.com'
  GG_APP_SECRET: 'tAXClscei57RbFamLojWdRMM'

postfinance:
  ACTION_URL: 'https://e-payment.postfinance.ch/ncol/test/orderstandard.asp'
  PSP: 'ciaoboxDEMO'
  HASHSEED: '123456.Cbx'
  TP: 'http://www.ciaobox.it/epayment.html'

invitation:
  URL: 'http://localhost:3000/invite/'

zoho:
  auth_token: 8191b6c216e8d6c3fd3a55965535495b
  organ_id: '89033694'
  hostedpage_redirect: 'http://localhost:3000/shipping/standard/confirmation'

detrack:
  api_key: 'ec5f7d4e6a0b508f3450cdfc942d946bf3c6f5acecd378ed'
  notify_email: 'sales@ciaobox.ch'
  collection_notify_url: 'http://localhost:3000/detrack/collection_notify'
  delivery_notify_url: 'http://localhost:3000/detrack/delivery_notify'