devise:
  FB_APP_ID: 174040969610369
  FB_APP_SECRET: b0781dc049e43bf88bc93a10c8f1fca8
  GG_APP_ID: '630017564342-bepruna5tsrmq9ojkvokknlt08sebu3a.apps.googleusercontent.com'
  GG_APP_SECRET: 'tAXClscei57RbFamLojWdRMM'

postfinance:
  ACTION_URL: 'https://e-payment.postfinance.ch/ncol/test/orderstandard.asp'
  PSP: 'ciaoboxDEMO'
  HASHSEED: '123456.Cbx'
  TP: 'http://www.ciaobox.it/epayment.html'

invitation:
  URL: 'http://ciaobox.it/invite/'

zoho:
  auth_token: 8191b6c216e8d6c3fd3a55965535495b
  organ_id: '135368668'
  hostedpage_redirect: 'http://ciaobox.it/shipping/standard/confirmation'

detrack:
  api_key: 55fea8bec5c911ecb9c355eb92bc7195bcd605c702ba80e0
  notify_email: 'sales@ciaobox.ch'
  collection_notify_url: 'http://ciaobox.it/detrack/collection_notify'
  delivery_notify_url: 'http://ciaobox.it/detrack/delivery_notify'
  photo_dir_path: '/home/ubuntu/ciaobox/current/public/images/order_item/photos/'
  photo_uri_path: '/images/order_item/photos/'